services:
  db:
    image: postgres:15
    container_name: justconnect_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
    container_name: justconnect_backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/justconnect
      JWT_SECRET: sua-chave-secreta
    volumes:
      - ./apps/backend:/app
    command: npm run dev

volumes:
  postgres_data:
